export const SET_WALLPAPERS = "SET_WALLPAPERS";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const SET_FAVORITE = "SET_FAVORITE";

export const LOAD_FAVORITES = "LOAD_FAVORITES";

export const SAVE_ICONS = "SAVE_ICONS";

export const SHARE_DIALOG_VISIBLE = "SHARE_DIALOG_VISIBLE";
export const SHARE_DIALOG_INVISIBLE = "SHARE_DIALOG_INVISIBLE";

export const MORE_OPTIONS_VISIBLE = "MORE_OPTIONS_VISIBLE";
export const MORE_OPTIONS_INVISIBLE = "MORE_OPTIONS_INVISIBLE";

export const MODAL_BOX_VISIBLE = "MODAL_BOX_VISIBLE";
export const MODAL_BOX_INVISIBLE = "MODAL_BOX_INVISIBLE";

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
